### ISSUE TITLE
Disable "postinstall" script in published package

### ISSUE THREAD

**Issue by nkahnfr** [eavam/use-debouncy#477]
Hello.

First of all, thank you for your package.

I am having issue installing it as a dependency since your `postinstall` script is executed and so tries to install husky (which fails since the command is not run in my project root directory).
My understanding is that you should use `prepare` instead of `postinstall` (if using npm) or use [pinst](https://github.com/typicode/pinst) to to disable `postinstall` when publishing your package.

Let me know if I missed something.

Thanks,

Nicolas

**Comment by eavam** [comment]
Hi! 
Thanks for the report. I made a pull request (#493) for fixed its bug.
