### ISSUE TITLE
renderFrame is using `Date.now` to initialize the callback start time instead of requestAnimationFrame first argument

### ISSUE THREAD

**Issue by nkahnfr** [eavam/use-debouncy#496]
Hi,

I think there is a bug in latest version that is reproduced here: https://codesandbox.io/s/reproduce-use-debouncy-bug-yx40d
You'll notice that nothing appears in the console when you're typing in the input text.

My guess is that you're using `Date.now()` to [setup `timeStart` argument of `renderFrame` callback](https://github.com/eavam/use-debouncy/blob/main/src/core.ts#L18) whereas `window.requestAnimationFrame()` method is passing a DOMHighResTimeStamp (similar to the one returned by `performance.now()`) as the single argument to the callback function.

**Comment by nkahnfr** [comment]
The following commit seems to fix the issue (at least for the application used with Cypress): https://github.com/nkahnfr/use-debouncy/commit/547543d8febb7e0f4862acf048f474a993f218f6

**Comment by eavam** [comment]
Hi @nkahnfr!
Thanks for this report. This is a stupid bug I have seen in the past. I trusted the tests and didn't check the release :(
Now I have rolled back to the stable version. I need time to sort out the tests.
Thanks again.
