### ISSUE TITLE
This expression is not callable.

### ISSUE THREAD

**Issue by adamgogogo** [eavam/use-debouncy#829]
This expression is not callable.
  Type 'typeof import("./node_modules/use-debouncy/lib/index")' has no call signatures.ts(2349)

**Comment by eavam** [comment]
Hi!
Can you add some code to reproduce the problem? Or some additional description.

**Comment by BraydenTW** [comment]
Hey same issue here. It doesn't work on TS projects.

```tsx
import prisma from '@/lib/prisma'
import { useSession } from 'next-auth/react'
import React, { useCallback, useState } from 'react'
import useDebouncy from 'use-debouncy/effect'

function Create() {
  const [val, setVal] = useState(val)
  useDebouncy(
      () => {
        console.log('call API')
      },
      400,
      [val]
  }
  return (
    <div>
        <p>Hello world!</p>
    </div>
  )
}

export default Create
```

<img width="525" alt="image" src="https://user-images.githubusercontent.com/47185402/150658545-5b1dfaf4-503f-45f7-9f9f-6d9e511661bd.png">

**Comment by BraydenTW** [comment]
But anyways @adamgogogo and @eavam I fixed it by importing it like this instead:

```tsx
import { useDebouncyEffect } from 'use-debouncy'
```

**Comment by wschenkel** [comment]
@BraydenTW Thanks, it helped me a lot!

**Comment by BraydenTW** [comment]
You’re welcome!
